name: Github Actions
on: [push, pull_request]
jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]
        nim-version: ['1.4.x', 'stable']

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2
    - uses: jiro4989/setup-nim-action@v1
      with:
        nim-version: ${{ matrix.nim-version }}
    - run: nimble test --gc:arc -d:release -y
    - run: nimble test --gc:arc -d:release -d:pixieNoSimd -y
    - run: nimble test --gc:orc -d:release -y
    - run: nim cpp --gc:orc -d:release -r tests/all.nim
